const GET_REPOS = 'GET_REPOS';
const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
const GET_REPOS_FAILURE = 'GET_REPOS_FAILURE';
const GET_USER_DETAILS = 'GET_USER_DETAILS';
const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE'; 
const SEARCH_REPOS = 'SEARCH_REPOS';
const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
const SEARCH_REPOS_FAILURE = 'SEARCH_REPOS_FAILURE';
const GET_CONTRIBUTOR_DETAILS = 'GET_CONTRIBUTOR_DETAILS';
const GET_CONTRIBUTOR_DETAILS_SUCCESS = 'GET_CONTRIBUTOR_DETAILS_SUCCESS';
const GET_CONTRIBUTOR_DETAILS_FAILURE = 'GET_CONTRIBUTOR_DETAILS_FAILURE';

export {
    GET_REPOS,
    GET_REPOS_SUCCESS,
    GET_REPOS_FAILURE,
    GET_USER_DETAILS,
    GET_USER_DETAILS_SUCCESS,
    GET_USER_DETAILS_FAILURE,
    SEARCH_REPOS,
    SEARCH_REPOS_SUCCESS,
    SEARCH_REPOS_FAILURE,
    GET_CONTRIBUTOR_DETAILS,
    GET_CONTRIBUTOR_DETAILS_SUCCESS,
    GET_CONTRIBUTOR_DETAILS_FAILURE
};